name: Build and deploy Node.js app to Azure Web App - backend-prograweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies, build and test in /server/Back_PrograWeb
        working-directory: server/Back_PrograWeb
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip the backend for deployment
        run: |
          cd server/Back_PrograWeb
          zip -r ../../release.zip .

      - name: Upload artifact for deploy step
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CC7D9E650D3D40EA9B0623D281A08ABE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A727E2B2CD334891977C3648D3666A99 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_29370CEB1E91468AB5938D87466C522B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-prograweb'
          slot-name: 'Production'
          package: .
